/**
 * 监管机构数据
 * 用于 regulators 列表页和详情页共享数据
 */

export interface RegulatoryAgency {
  id: string;
  country: string;
  country_code: string;
  agency_name: string;
  agency_name_en: string;
  agency_name_zh: string;
  agency_type: string;
  official_website: string;
  database_url: string;
  contact_email: string;
  contact_phone: string;
  contact_fax?: string;
  contact_address?: string;
  description: string;
  description_zh: string;
  verified: boolean;
  establishment_date?: string;
  parent_organization?: string;
  regulatory_framework?: string;
  device_classification_system?: string;
  approval_process_description?: string;
  average_approval_time?: string;
  official_fees?: string;
  languages_supported?: string[];
}

// 监管机构完整数据
export const regulatoryAgenciesData: RegulatoryAgency[] = [
  {
    id: '1',
    country: 'United States',
    country_code: 'US',
    agency_name: 'Food and Drug Administration',
    agency_name_en: 'Food and Drug Administration',
    agency_name_zh: '美国食品药品监督管理局',
    agency_type: 'national',
    official_website: 'https://www.fda.gov',
    database_url: 'https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfRL/rl.cfm',
    contact_email: 'info@fda.gov',
    contact_phone: '+1-888-463-6332',
    contact_fax: '+1-301-827-0111',
    contact_address: '10903 New Hampshire Avenue, Silver Spring, MD 20993, USA',
    description: 'The FDA is responsible for protecting the public health by ensuring the safety, efficacy, and security of human drugs, biological products, and medical devices.',
    description_zh: 'FDA 负责通过确保人用药品、生物制品和医疗器械的安全性、有效性和安全性来保护公众健康。',
    verified: true,
    establishment_date: '1906-06-30',
    parent_organization: 'Department of Health and Human Services',
    regulatory_framework: 'Federal Food, Drug, and Cosmetic Act (FD&C Act)',
    device_classification_system: 'Class I, Class II, Class III (based on risk)',
    approval_process_description: 'Medical devices must undergo premarket notification (510(k)) or premarket approval (PMA) depending on their classification.',
    average_approval_time: '510(k): 90 days; PMA: 180 days',
    official_fees: '510(k): $12,676; PMA: $289,232',
    languages_supported: ['English'],
  },
  {
    id: '2',
    country: 'China',
    country_code: 'CN',
    agency_name: 'National Medical Products Administration',
    agency_name_en: 'National Medical Products Administration',
    agency_name_zh: '国家药品监督管理局',
    agency_type: 'national',
    official_website: 'https://www.nmpa.gov.cn',
    database_url: 'https://www.nmpa.gov.cn/datasearch/home-index.html',
    contact_email: 'webmaster@nmpa.gov.cn',
    contact_phone: '+86-10-88330000',
    contact_address: 'No. 1 Xuanwumen Xidajie, Xicheng District, Beijing, China',
    description: 'NMPA is responsible for the supervision and administration of drugs, medical devices, and cosmetics in China.',
    description_zh: 'NMPA 负责中国境内药品、医疗器械和化妆品的监督管理。',
    verified: true,
    establishment_date: '2018-03-17',
    parent_organization: 'State Administration for Market Regulation',
    regulatory_framework: 'Regulations on Supervision and Administration of Medical Devices',
    device_classification_system: 'Class I, Class II, Class III (based on risk)',
    approval_process_description: 'Class I devices require filing, Class II and III require registration with technical review.',
    average_approval_time: 'Class II: 60-90 days; Class III: 90-120 days',
    official_fees: 'Registration fee varies by device class',
    languages_supported: ['Chinese'],
  },
  {
    id: '3',
    country: 'European Union',
    country_code: 'EU',
    agency_name: 'European Commission - DG SANTE',
    agency_name_en: 'European Commission - DG SANTE',
    agency_name_zh: '欧盟委员会 - 卫生与食品安全总局',
    agency_type: 'regional',
    official_website: 'https://health.ec.europa.eu',
    database_url: 'https://eudamed.ec.europa.eu',
    contact_email: 'sante-info@ec.europa.eu',
    contact_phone: '+32-2-2991111',
    contact_address: 'Rue Froissart 101, 1049 Brussels, Belgium',
    description: 'DG SANTE develops and implements EU policies on health and food safety, including medical devices regulation.',
    description_zh: 'DG SANTE 制定和实施欧盟卫生与食品安全政策，包括医疗器械法规。',
    verified: true,
    establishment_date: '1958-01-01',
    parent_organization: 'European Commission',
    regulatory_framework: 'EU Medical Device Regulation (MDR) 2017/745',
    device_classification_system: 'Class I, IIa, IIb, III (based on risk)',
    approval_process_description: 'Devices require CE marking through notified body assessment based on classification.',
    average_approval_time: 'Varies by notified body and device class: 3-12 months',
    official_fees: 'Varies by notified body',
    languages_supported: ['English', 'French', 'German', 'Spanish', 'Italian'],
  },
  {
    id: '4',
    country: 'Japan',
    country_code: 'JP',
    agency_name: 'Pharmaceuticals and Medical Devices Agency',
    agency_name_en: 'Pharmaceuticals and Medical Devices Agency',
    agency_name_zh: '独立行政法人医药品医疗器械综合机构',
    agency_type: 'national',
    official_website: 'https://www.pmda.go.jp',
    database_url: 'https://www.pmda.go.jp/english/',
    contact_email: 'info@pmda.go.jp',
    contact_phone: '+81-3-3506-9494',
    contact_address: '3-3-2 Kasumigaseki, Chiyoda-ku, Tokyo 100-0013, Japan',
    description: 'PMDA conducts scientific reviews and on-site inspections for pharmaceuticals and medical devices.',
    description_zh: 'PMDA 对药品和医疗器械进行科学审查和现场检查。',
    verified: true,
    establishment_date: '2004-04-01',
    parent_organization: 'Ministry of Health, Labour and Welfare',
    regulatory_framework: 'Pharmaceutical and Medical Device Act (PMD Act)',
    device_classification_system: 'Class I, II, III, IV (based on risk)',
    approval_process_description: 'Foreign manufacturers must obtain marketing approval and manufacturing site registration.',
    average_approval_time: 'Class II: 3-6 months; Class III/IV: 6-12 months',
    official_fees: 'Marketing approval: ¥1,227,900 - ¥2,455,800',
    languages_supported: ['Japanese', 'English'],
  },
  {
    id: '5',
    country: 'Canada',
    country_code: 'CA',
    agency_name: 'Health Canada - Medical Devices Bureau',
    agency_name_en: 'Health Canada - Medical Devices Bureau',
    agency_name_zh: '加拿大卫生部 - 医疗器械局',
    agency_type: 'national',
    official_website: 'https://www.canada.ca/en/health-canada',
    database_url: 'https://health-products.canada.ca/mdall-limh',
    contact_email: 'mdbh-dimsc@hc-sc.gc.ca',
    contact_phone: '+1-613-957-2911',
    contact_address: '101 Tunney\'s Pasture Driveway, Ottawa, ON K1A 0K9, Canada',
    description: 'Health Canada regulates medical devices to ensure their safety, efficacy, and quality.',
    description_zh: '加拿大卫生部监管医疗器械，确保其安全性、有效性和质量。',
    verified: true,
    establishment_date: '1996-01-01',
    parent_organization: 'Health Canada',
    regulatory_framework: 'Medical Devices Regulations (SOR/98-282)',
    device_classification_system: 'Class I, II, III, IV (based on risk)',
    approval_process_description: 'Class I devices require establishment license; Class II-IV require device license.',
    average_approval_time: 'Class II: 15 days; Class III: 75 days; Class IV: 90 days',
    official_fees: 'Device license: $7,994 - $11,652 CAD',
    languages_supported: ['English', 'French'],
  },
  {
    id: '6',
    country: 'Australia',
    country_code: 'AU',
    agency_name: 'Therapeutic Goods Administration',
    agency_name_en: 'Therapeutic Goods Administration',
    agency_name_zh: '澳大利亚治疗用品管理局',
    agency_type: 'national',
    official_website: 'https://www.tga.gov.au',
    database_url: 'https://www.tga.gov.au/resources/artg',
    contact_email: 'info@tga.gov.au',
    contact_phone: '+61-2-6289-3000',
    contact_address: '136 Narrabundah Lane, Symonston ACT 2609, Australia',
    description: 'TGA regulates therapeutic goods including medicines, medical devices, and biologicals.',
    description_zh: 'TGA 监管治疗用品，包括药品、医疗器械和生物制品。',
    verified: true,
    establishment_date: '1991-01-01',
    parent_organization: 'Australian Government Department of Health',
    regulatory_framework: 'Therapeutic Goods Act 1989',
    device_classification_system: 'Class I, IIa, IIb, III, AIMD (based on risk)',
    approval_process_description: 'Devices must be included in the Australian Register of Therapeutic Goods (ARTG).',
    average_approval_time: 'Class II: 30-60 days; Class III: 90-180 days',
    official_fees: 'Application fees: $1,070 - $8,550 AUD',
    languages_supported: ['English'],
  },
  {
    id: '7',
    country: 'United Kingdom',
    country_code: 'GB',
    agency_name: 'Medicines and Healthcare products Regulatory Agency',
    agency_name_en: 'Medicines and Healthcare products Regulatory Agency',
    agency_name_zh: '英国药品和保健品监管机构',
    agency_type: 'national',
    official_website: 'https://www.gov.uk/government/organisations/medicines-and-healthcare-products-regulatory-agency',
    database_url: 'https://www.gov.uk/guidance/medical-devices-software-and-apps',
    contact_email: 'info@mhra.gov.uk',
    contact_phone: '+44-20-3080-6000',
    contact_address: '10 South Colonnade, Canary Wharf, London E14 4PU, UK',
    description: 'MHRA regulates medicines, medical devices and blood components for transfusion in the UK.',
    description_zh: 'MHRA 监管英国境内的药品、医疗器械和输血用血液制品。',
    verified: true,
    establishment_date: '2003-04-01',
    parent_organization: 'Department of Health and Social Care',
    regulatory_framework: 'UK Medical Devices Regulations 2002',
    device_classification_system: 'Class I, IIa, IIb, III (based on risk)',
    approval_process_description: 'Post-Brexit, UKCA marking required for Great Britain market.',
    average_approval_time: 'Varies by device class: 1-6 months',
    official_fees: 'Registration fees vary by device class',
    languages_supported: ['English'],
  },
  {
    id: '8',
    country: 'South Korea',
    country_code: 'KR',
    agency_name: 'Ministry of Food and Drug Safety',
    agency_name_en: 'Ministry of Food and Drug Safety',
    agency_name_zh: '韩国食品药品安全部',
    agency_type: 'national',
    official_website: 'https://www.mfds.go.kr',
    database_url: 'https://www.mfds.go.kr/eng/index.do',
    contact_email: 'webmaster@mfds.go.kr',
    contact_phone: '+82-43-719-1000',
    contact_address: '187 Osongsaengmyeong 2-ro, Osong-eup, Heungdeok-gu, Cheongju-si, Chungcheongbuk-do, Korea',
    description: 'MFDS regulates foods, drugs, medical devices, and cosmetics to ensure public health.',
    description_zh: 'MFDS 监管食品、药品、医疗器械和化妆品，确保公众健康。',
    verified: true,
    establishment_date: '1998-01-01',
    parent_organization: 'Government of South Korea',
    regulatory_framework: 'Medical Device Act',
    device_classification_system: 'Class I, II, III, IV (based on risk)',
    approval_process_description: 'Product approval and manufacturing site registration required.',
    average_approval_time: 'Class II: 30-60 days; Class III/IV: 60-90 days',
    official_fees: 'Approval fees vary by device class',
    languages_supported: ['Korean', 'English'],
  },
  {
    id: '9',
    country: 'Singapore',
    country_code: 'SG',
    agency_name: 'Health Sciences Authority',
    agency_name_en: 'Health Sciences Authority',
    agency_name_zh: '新加坡卫生科学局',
    agency_type: 'national',
    official_website: 'https://www.hsa.gov.sg',
    database_url: 'https://www.hsa.gov.sg/medical-devices',
    contact_email: 'hsa_info@hsa.gov.sg',
    contact_phone: '+65-6866-3500',
    contact_address: '11 Biopolis Way, #11-01 Helios, Singapore 138667',
    description: 'HSA regulates medical devices, pharmaceuticals, and health products in Singapore.',
    description_zh: 'HSA 监管新加坡境内的医疗器械、药品和健康产品。',
    verified: true,
    establishment_date: '2001-07-01',
    parent_organization: 'Ministry of Health',
    regulatory_framework: 'Health Products Act',
    device_classification_system: 'Class A, B, C, D (based on risk)',
    approval_process_description: 'Devices require registration before import or sale in Singapore.',
    average_approval_time: 'Class B: 30 days; Class C: 60 days; Class D: 90 days',
    official_fees: 'Registration fees: S$100 - S$1,200',
    languages_supported: ['English'],
  },
  {
    id: '10',
    country: 'Brazil',
    country_code: 'BR',
    agency_name: 'Agência Nacional de Vigilância Sanitária',
    agency_name_en: 'National Health Surveillance Agency',
    agency_name_zh: '巴西国家卫生监督局',
    agency_type: 'national',
    official_website: 'https://www.gov.br/anvisa/pt-br',
    database_url: 'https://consultas.anvisa.gov.br/#/saude/',
    contact_email: 'ouvidoria@anvisa.gov.br',
    contact_phone: '+55-61-3462-5000',
    contact_address: 'SIA Trecho 5, Área Especial 57, Brasília-DF, 71205-050, Brazil',
    description: 'ANVISA regulates health products including medical devices, pharmaceuticals, and cosmetics.',
    description_zh: 'ANVISA 监管健康产品，包括医疗器械、药品和化妆品。',
    verified: true,
    establishment_date: '1999-01-26',
    parent_organization: 'Ministry of Health',
    regulatory_framework: 'RDC 185/2001 and related resolutions',
    device_classification_system: 'Class I, II, III, IV (based on risk)',
    approval_process_description: 'Registration required with Brazilian Registration Holder (BRH).',
    average_approval_time: 'Class I/II: 3-6 months; Class III/IV: 6-12 months',
    official_fees: 'Registration fees vary by device class',
    languages_supported: ['Portuguese'],
  },
  {
    id: '11',
    country: 'India',
    country_code: 'IN',
    agency_name: 'Central Drugs Standard Control Organization',
    agency_name_en: 'Central Drugs Standard Control Organization',
    agency_name_zh: '印度中央药品标准控制组织',
    agency_type: 'national',
    official_website: 'https://cdsco.gov.in',
    database_url: 'https://cdsco.gov.in/opencms/opencms/en/Home/',
    contact_email: 'dcgi@cdsco.nic.in',
    contact_phone: '+91-11-2763-6834',
    contact_address: 'FDA Bhawan, Kotla Road, New Delhi - 110002, India',
    description: 'CDSCO regulates pharmaceuticals, medical devices, and cosmetics in India.',
    description_zh: 'CDSCO 监管印度境内的药品、医疗器械和化妆品。',
    verified: true,
    establishment_date: '1945-01-01',
    parent_organization: 'Ministry of Health and Family Welfare',
    regulatory_framework: 'Drugs and Cosmetics Act, 1940',
    device_classification_system: 'Class A, B, C, D (based on risk)',
    approval_process_description: 'Import license and registration required for medical devices.',
    average_approval_time: 'Varies by device class: 3-9 months',
    official_fees: 'Registration fees vary by device class',
    languages_supported: ['English', 'Hindi'],
  },
  {
    id: '12',
    country: 'Switzerland',
    country_code: 'CH',
    agency_name: 'Swissmedic',
    agency_name_en: 'Swiss Agency for Therapeutic Products',
    agency_name_zh: '瑞士治疗产品管理局',
    agency_type: 'national',
    official_website: 'https://www.swissmedic.ch',
    database_url: 'https://www.swissmedic.ch/swissmedic/en/home/medical-devices.html',
    contact_email: 'info@swissmedic.ch',
    contact_phone: '+41-58-462-21-11',
    contact_address: 'Hallerstrasse 7, 3012 Bern, Switzerland',
    description: 'Swissmedic regulates medicines and medical devices in Switzerland.',
    description_zh: 'Swissmedic 监管瑞士境内的药品和医疗器械。',
    verified: true,
    establishment_date: '2002-01-01',
    parent_organization: 'Federal Department of Home Affairs',
    regulatory_framework: 'Medical Devices Ordinance (MedDO)',
    device_classification_system: 'Class I, IIa, IIb, III (based on risk)',
    approval_process_description: 'CH-Rep required for foreign manufacturers; registration mandatory.',
    average_approval_time: 'Varies by device class: 1-6 months',
    official_fees: 'Registration fees vary by device class',
    languages_supported: ['German', 'French', 'Italian', 'English'],
  },
];

// 国家名称映射
export const countryNames: Record<string, { zh: string; en: string }> = {
  'United States': { zh: '美国', en: 'United States' },
  'China': { zh: '中国', en: 'China' },
  'European Union': { zh: '欧盟', en: 'European Union' },
  'Japan': { zh: '日本', en: 'Japan' },
  'Canada': { zh: '加拿大', en: 'Canada' },
  'Australia': { zh: '澳大利亚', en: 'Australia' },
  'United Kingdom': { zh: '英国', en: 'United Kingdom' },
  'South Korea': { zh: '韩国', en: 'South Korea' },
  'Singapore': { zh: '新加坡', en: 'Singapore' },
  'Brazil': { zh: '巴西', en: 'Brazil' },
  'India': { zh: '印度', en: 'India' },
  'Switzerland': { zh: '瑞士', en: 'Switzerland' },
  'Saudi Arabia': { zh: '沙特阿拉伯', en: 'Saudi Arabia' },
  'Mexico': { zh: '墨西哥', en: 'Mexico' },
  'Turkey': { zh: '土耳其', en: 'Turkey' },
  'Russia': { zh: '俄罗斯', en: 'Russia' },
  'South Africa': { zh: '南非', en: 'South Africa' },
  'Thailand': { zh: '泰国', en: 'Thailand' },
  'Vietnam': { zh: '越南', en: 'Vietnam' },
  'Indonesia': { zh: '印度尼西亚', en: 'Indonesia' },
};

// 根据ID获取监管机构
export function getAgencyById(id: string): RegulatoryAgency | undefined {
  return regulatoryAgenciesData.find(agency => agency.id === id);
}

// 获取所有监管机构
export function getAllAgencies(): RegulatoryAgency[] {
  return regulatoryAgenciesData;
}
